// GovFlow mock data layer — realistic Indian government interoperability data.

export type Health = "Healthy" | "Degraded" | "Down";
export type Role = "Admin" | "Department Officer" | "Developer" | "Operator" | "Auditor" | "Citizen";

export const ROLES: Role[] = ["Admin", "Department Officer", "Developer", "Operator", "Auditor"];

export type City = {
  id: string;
  city: string;
  district: string;
  state: string;
  country: string;
  systems: number;
  load: number; // multiplier for mock metrics
};

export const LOCATIONS: City[] = [
  {
    id: "nashik",
    city: "Nashik",
    district: "Nashik",
    state: "Maharashtra",
    country: "India",
    systems: 5,
    load: 1,
  },
  {
    id: "pune",
    city: "Pune",
    district: "Pune",
    state: "Maharashtra",
    country: "India",
    systems: 8,
    load: 1.6,
  },
  {
    id: "mumbai",
    city: "Mumbai",
    district: "Mumbai Suburban",
    state: "Maharashtra",
    country: "India",
    systems: 11,
    load: 2.4,
  },
  {
    id: "delhi",
    city: "New Delhi",
    district: "New Delhi",
    state: "Delhi",
    country: "India",
    systems: 12,
    load: 2.7,
  },
  {
    id: "bengaluru",
    city: "Bengaluru",
    district: "Bengaluru Urban",
    state: "Karnataka",
    country: "India",
    systems: 9,
    load: 1.9,
  },
  {
    id: "hyderabad",
    city: "Hyderabad",
    district: "Hyderabad",
    state: "Telangana",
    country: "India",
    systems: 7,
    load: 1.4,
  },
];

export const getLocation = (id: string) => LOCATIONS.find((l) => l.id === id) ?? LOCATIONS[0]!;

/* ------------------------------- services -------------------------------- */

export type Service = {
  id: string;
  name: string;
  code: string;
  category: string;
  department: string;
  sla: string;
  fee: string;
  workflowId: string;
  summary: string;
  documents: string[];
  eligibility: string[];
  systems: string[];
  volume: number;
};

export const SERVICES: Service[] = [
  {
    id: "scholarship",
    name: "Post-Matric Scholarship",
    code: "SCH",
    category: "Education",
    department: "Education Department",
    sla: "14 days",
    fee: "Free",
    workflowId: "wf-scholarship",
    summary:
      "Merit-cum-means scholarship for post-matric students, orchestrated across education, revenue, banking and welfare systems.",
    documents: ["Aadhaar", "Income Certificate", "Marksheet", "Bank Passbook"],
    eligibility: [
      "Family income below ₹2.5L",
      "Enrolled in recognised institution",
      "Minimum 60% in last exam",
    ],
    systems: ["Aadhaar eKYC", "SAMARTH Education API", "PFMS Banking", "Income Tax Verification"],
    volume: 1284,
  },
  {
    id: "income-certificate",
    name: "Income Certificate",
    code: "INC",
    category: "Revenue",
    department: "Revenue Department",
    sla: "7 days",
    fee: "₹50",
    workflowId: "wf-income",
    summary:
      "Digitally verified income certificate issued from revenue, tax and employment records without manual affidavits.",
    documents: ["Aadhaar", "Ration Card", "Salary Slip / ITR"],
    eligibility: ["Resident of the district", "Valid Aadhaar linkage"],
    systems: ["Aadhaar eKYC", "Income Tax Verification", "Land Records (Legacy)"],
    volume: 2140,
  },
  {
    id: "residence-certificate",
    name: "Residence Certificate",
    code: "RES",
    category: "Revenue",
    department: "Revenue Department",
    sla: "5 days",
    fee: "₹30",
    workflowId: "wf-residence",
    summary:
      "Proof of domicile generated by cross-checking electoral, utility and municipal property records.",
    documents: ["Aadhaar", "Electricity Bill", "Voter ID"],
    eligibility: ["Continuous residence of 3+ years"],
    systems: ["Aadhaar eKYC", "Municipal Property SOAP", "Electoral Roll"],
    volume: 1670,
  },
  {
    id: "pension",
    name: "Senior Citizen Pension",
    code: "PEN",
    category: "Social Welfare",
    department: "Social Welfare Department",
    sla: "21 days",
    fee: "Free",
    workflowId: "wf-pension",
    summary:
      "Old-age pension sanction with automated life certificate, income and bank account validation.",
    documents: ["Aadhaar", "Age Proof", "Bank Passbook"],
    eligibility: ["Age 60+", "BPL household", "No government pension"],
    systems: ["Aadhaar eKYC", "PFMS Banking", "Jeevan Pramaan"],
    volume: 940,
  },
  {
    id: "subsidy",
    name: "LPG / Utility Subsidy",
    code: "SUB",
    category: "Social Welfare",
    department: "Food & Civil Supplies",
    sla: "10 days",
    fee: "Free",
    workflowId: "wf-subsidy",
    summary:
      "Direct benefit transfer subsidy enrolment with consent-bound bank and ration linkage.",
    documents: ["Aadhaar", "Ration Card", "Bank Passbook"],
    eligibility: ["Active ration card", "Aadhaar seeded bank account"],
    systems: ["Aadhaar eKYC", "PFMS Banking", "PDS Legacy Mainframe"],
    volume: 1320,
  },
  {
    id: "business-registration",
    name: "Business / Shop Registration",
    code: "BIZ",
    category: "Commerce",
    department: "Municipal Corporation",
    sla: "12 days",
    fee: "₹1,200",
    workflowId: "wf-business",
    summary:
      "Single-window trade licence combining GST, municipal, fire-safety and labour clearances.",
    documents: ["PAN", "GST Certificate", "Rent Agreement", "Site Plan"],
    eligibility: ["Valid GSTIN", "Approved commercial premises"],
    systems: ["GSTN REST API", "Municipal Property SOAP", "Fire Safety Registry"],
    volume: 610,
  },
  {
    id: "farmer-assistance",
    name: "Farmer Assistance Scheme",
    code: "FRM",
    category: "Agriculture",
    department: "Agriculture Department",
    sla: "15 days",
    fee: "Free",
    workflowId: "wf-farmer",
    summary:
      "Crop-loss and input-support assistance driven by land record, soil health and weather data exchange.",
    documents: ["Aadhaar", "7/12 Land Extract", "Bank Passbook"],
    eligibility: ["Registered cultivator", "Land holding under 5 hectares"],
    systems: ["Land Records (Legacy)", "Agri Market SOAP", "PFMS Banking"],
    volume: 880,
  },
];

/* ----------------------------- departments ------------------------------- */

export type Department = {
  id: string;
  name: string;
  head: string;
  services: string[];
  systems: string[];
  health: Health;
  responseMs: number;
  uptime: number;
};

export const DEPARTMENTS: Department[] = [
  {
    id: "revenue",
    name: "Revenue Department",
    head: "Smt. Anjali Deshmukh",
    services: ["income-certificate", "residence-certificate"],
    systems: ["int-aadhaar", "int-landrecords"],
    health: "Healthy",
    responseMs: 320,
    uptime: 99.8,
  },
  {
    id: "education",
    name: "Education Department",
    head: "Dr. Rajesh Kulkarni",
    services: ["scholarship"],
    systems: ["int-samarth", "int-aadhaar"],
    health: "Healthy",
    responseMs: 410,
    uptime: 99.5,
  },
  {
    id: "welfare",
    name: "Social Welfare Department",
    head: "Shri Prakash Jadhav",
    services: ["pension"],
    systems: ["int-jeevan", "int-pfms"],
    health: "Degraded",
    responseMs: 1200,
    uptime: 97.1,
  },
  {
    id: "banking",
    name: "Banking Partners (PFMS)",
    head: "Shri Nitin Rao",
    services: ["scholarship", "pension", "subsidy"],
    systems: ["int-pfms"],
    health: "Healthy",
    responseMs: 380,
    uptime: 99.6,
  },
  {
    id: "agriculture",
    name: "Agriculture Department",
    head: "Smt. Meera Pawar",
    services: ["farmer-assistance"],
    systems: ["int-agrimarket", "int-landrecords"],
    health: "Healthy",
    responseMs: 290,
    uptime: 99.9,
  },
  {
    id: "supplies",
    name: "Food & Civil Supplies",
    head: "Shri Vikas Patil",
    services: ["subsidy"],
    systems: ["int-pds"],
    health: "Degraded",
    responseMs: 1450,
    uptime: 96.4,
  },
  {
    id: "municipal",
    name: "Municipal Corporation",
    head: "Shri Sandeep More",
    services: ["business-registration", "residence-certificate"],
    systems: ["int-municipal", "int-gstn"],
    health: "Healthy",
    responseMs: 470,
    uptime: 99.2,
  },
];

/* ----------------------------- integrations ------------------------------ */

export type Integration = {
  id: string;
  name: string;
  protocol: "REST / JSON" | "SOAP / XML" | "Legacy / Flat File";
  owner: string;
  health: Health;
  successRate: number;
  latencyMs: number;
  uptime: number;
  failures24h: number;
  auth: string;
  baseUrl: string;
  endpoints: { method: string; path: string; desc: string }[];
  sampleRequest: string;
  sampleResponse: string;
  schema: string[];
};

export const INTEGRATIONS: Integration[] = [
  {
    id: "int-aadhaar",
    name: "Aadhaar eKYC Gateway",
    protocol: "REST / JSON",
    owner: "UIDAI",
    health: "Healthy",
    successRate: 99.4,
    latencyMs: 240,
    uptime: 99.9,
    failures24h: 3,
    auth: "OAuth 2.0 + mTLS",
    baseUrl: "https://api.uidai.gov.in/ekyc/v2",
    endpoints: [
      { method: "POST", path: "/verify", desc: "Verify Aadhaar with OTP consent" },
      { method: "GET", path: "/kyc/{txnId}", desc: "Fetch demographic KYC payload" },
    ],
    sampleRequest: `{
  "uid": "XXXX-XXXX-4821",
  "txnId": "GF-TXN-90231",
  "consentArtefact": "CA-2026-77431"
}`,
    sampleResponse: `{
  "status": "VERIFIED",
  "citizen_name": "Ramesh Patil",
  "dob": "1998-04-12",
  "mobile_no": "+91-98XXXXXX21",
  "address": { "district": "Nashik", "state": "Maharashtra" }
}`,
    schema: [
      "uid: string",
      "citizen_name: string",
      "dob: date",
      "mobile_no: string",
      "address: object",
    ],
  },
  {
    id: "int-samarth",
    name: "SAMARTH Education API",
    protocol: "REST / JSON",
    owner: "Ministry of Education",
    health: "Degraded",
    successRate: 94.2,
    latencyMs: 980,
    uptime: 97.8,
    failures24h: 41,
    auth: "API Key + HMAC",
    baseUrl: "https://samarth.edu.gov.in/api/v1",
    endpoints: [
      { method: "GET", path: "/student/{enrolmentNo}", desc: "Enrolment and marks verification" },
      { method: "POST", path: "/institution/verify", desc: "Institution recognition check" },
    ],
    sampleRequest: `{ "enrolmentNo": "MH-NSK-2024-88213", "academicYear": "2025-26" }`,
    sampleResponse: `{
  "student_full_name": "Ramesh Patil",
  "institution": "K.K. Wagh College, Nashik",
  "percentage": 78.4,
  "status": "ENROLLED"
}`,
    schema: [
      "enrolmentNo: string",
      "student_full_name: string",
      "institution: string",
      "percentage: number",
    ],
  },
  {
    id: "int-pfms",
    name: "PFMS Banking Bridge",
    protocol: "REST / JSON",
    owner: "Ministry of Finance",
    health: "Healthy",
    successRate: 99.1,
    latencyMs: 380,
    uptime: 99.6,
    failures24h: 7,
    auth: "OAuth 2.0 (client credentials)",
    baseUrl: "https://pfms.nic.in/api/v3",
    endpoints: [
      { method: "POST", path: "/account/validate", desc: "Penny-drop bank account validation" },
      { method: "POST", path: "/dbt/transfer", desc: "Initiate direct benefit transfer" },
    ],
    sampleRequest: `{ "account_number": "XXXXXX8891", "ifsc": "SBIN0004321" }`,
    sampleResponse: `{ "accountHolder": "RAMESH PATIL", "valid": true, "bank": "State Bank of India" }`,
    schema: ["account_number: string", "ifsc: string", "accountHolder: string", "valid: boolean"],
  },
  {
    id: "int-landrecords",
    name: "Land Records Mainframe",
    protocol: "Legacy / Flat File",
    owner: "State Revenue Board",
    health: "Degraded",
    successRate: 91.7,
    latencyMs: 2100,
    uptime: 96.2,
    failures24h: 58,
    auth: "SFTP key exchange",
    baseUrl: "sftp://landrec.mh.gov.in/outbound",
    endpoints: [
      { method: "PULL", path: "/712_extract.dat", desc: "Nightly 7/12 extract dump" },
      { method: "PUSH", path: "/mutation_req.dat", desc: "Mutation request file" },
    ],
    sampleRequest: `SURVEY|NSK|2026|0043|REQ`,
    sampleResponse: `NAME=PATIL RAMESH S|AREA=1.42HA|VILLAGE=OZAR|TYPE=AGRI`,
    schema: ["NAME: fixed(40)", "AREA: fixed(8)", "VILLAGE: fixed(20)", "TYPE: fixed(6)"],
  },
  {
    id: "int-municipal",
    name: "Municipal Property SOAP",
    protocol: "SOAP / XML",
    owner: "Urban Local Body",
    health: "Healthy",
    successRate: 98.3,
    latencyMs: 640,
    uptime: 99.1,
    failures24h: 12,
    auth: "WS-Security UsernameToken",
    baseUrl: "https://ulb.gov.in/services/PropertyService",
    endpoints: [
      { method: "POST", path: "#getPropertyDetails", desc: "Property tax and ownership details" },
      { method: "POST", path: "#getTradeLicence", desc: "Trade licence status" },
    ],
    sampleRequest: `<soap:Envelope><soap:Body>
  <getPropertyDetails><propertyId>NSK-PT-99213</propertyId></getPropertyDetails>
</soap:Body></soap:Envelope>`,
    sampleResponse: `<PropertyDetails>
  <OwnerName>Ramesh Patil</OwnerName>
  <Ward>12</Ward>
  <TaxStatus>PAID</TaxStatus>
</PropertyDetails>`,
    schema: ["propertyId: string", "OwnerName: string", "Ward: string", "TaxStatus: enum"],
  },
  {
    id: "int-gstn",
    name: "GSTN Taxpayer API",
    protocol: "REST / JSON",
    owner: "GST Network",
    health: "Healthy",
    successRate: 99.7,
    latencyMs: 300,
    uptime: 99.9,
    failures24h: 1,
    auth: "API Key",
    baseUrl: "https://api.gst.gov.in/taxpayer/v1",
    endpoints: [{ method: "GET", path: "/{gstin}", desc: "Taxpayer profile and filing status" }],
    sampleRequest: `{ "gstin": "27AAECG1234M1Z8" }`,
    sampleResponse: `{ "legalName": "Patil Traders", "status": "ACTIVE", "filingUpToDate": true }`,
    schema: ["gstin: string", "legalName: string", "status: enum", "filingUpToDate: boolean"],
  },
  {
    id: "int-jeevan",
    name: "Jeevan Pramaan Life Cert.",
    protocol: "SOAP / XML",
    owner: "MeitY",
    health: "Down",
    successRate: 62.4,
    latencyMs: 4200,
    uptime: 88.3,
    failures24h: 143,
    auth: "Digital Signature Certificate",
    baseUrl: "https://jeevanpramaan.gov.in/ws/life",
    endpoints: [
      { method: "POST", path: "#getLifeCertificate", desc: "Pensioner life certificate status" },
    ],
    sampleRequest: `<getLifeCertificate><pensionId>MH-PEN-33121</pensionId></getLifeCertificate>`,
    sampleResponse: `<Fault><faultstring>Upstream biometric service unavailable</faultstring></Fault>`,
    schema: ["pensionId: string", "certificateDate: date", "status: enum"],
  },
  {
    id: "int-pds",
    name: "PDS Legacy Mainframe",
    protocol: "Legacy / Flat File",
    owner: "Food & Civil Supplies",
    health: "Degraded",
    successRate: 93.1,
    latencyMs: 1850,
    uptime: 96.4,
    failures24h: 49,
    auth: "VPN + batch credentials",
    baseUrl: "sftp://pds.mh.gov.in/batch",
    endpoints: [{ method: "PULL", path: "/ration_master.dat", desc: "Ration card master extract" }],
    sampleRequest: `RCQ|NSK|RC-88213`,
    sampleResponse: `RC=RC-88213|HEAD=PATIL RAMESH|MEMBERS=4|TYPE=APL`,
    schema: ["RC: fixed(12)", "HEAD: fixed(40)", "MEMBERS: fixed(2)", "TYPE: fixed(3)"],
  },
  {
    id: "int-agrimarket",
    name: "Agri Market Data Service",
    protocol: "SOAP / XML",
    owner: "Agriculture Department",
    health: "Healthy",
    successRate: 98.9,
    latencyMs: 520,
    uptime: 99.4,
    failures24h: 5,
    auth: "WS-Security",
    baseUrl: "https://agmarknet.gov.in/ws/market",
    endpoints: [
      { method: "POST", path: "#getCropPrices", desc: "Mandi price and crop-loss index" },
    ],
    sampleRequest: `<getCropPrices><district>Nashik</district><crop>Onion</crop></getCropPrices>`,
    sampleResponse: `<Prices><Modal>2150</Modal><Unit>Quintal</Unit></Prices>`,
    schema: ["district: string", "crop: string", "Modal: number"],
  },
];

/* ------------------------------ workflows -------------------------------- */

export type StageDef = {
  id: string;
  name: string;
  department: string;
  system: string;
  dataExchanged: string;
  api: string;
  ms: number;
  failsFirst?: boolean;
};

export type Workflow = {
  id: string;
  name: string;
  serviceId: string;
  version: string;
  status: "Published" | "Draft" | "Paused";
  runs: number;
  successRate: number;
  avgMinutes: number;
  stages: StageDef[];
};

const stage = (
  id: string,
  name: string,
  department: string,
  system: string,
  dataExchanged: string,
  api: string,
  ms: number,
  failsFirst = false,
): StageDef => ({ id, name, department, system, dataExchanged, api, ms, failsFirst });

export const WORKFLOWS: Workflow[] = [
  {
    id: "wf-scholarship",
    name: "Scholarship Application Orchestration",
    serviceId: "scholarship",
    version: "v4.2",
    status: "Published",
    runs: 1284,
    successRate: 98.7,
    avgMinutes: 6,
    stages: [
      stage(
        "submitted",
        "Application Submitted",
        "GovFlow Portal",
        "Citizen Gateway",
        "Application form, service code SCH",
        "POST /applications",
        210,
      ),
      stage(
        "auth",
        "Authentication",
        "UIDAI",
        "Aadhaar eKYC Gateway",
        "Aadhaar token, biometric consent",
        "POST /ekyc/verify",
        340,
      ),
      stage(
        "consent",
        "Consent Capture",
        "GovFlow Consent Layer",
        "Consent Artefact Registry",
        "Purpose, scope, expiry, recipient",
        "POST /consent/artefact",
        180,
      ),
      stage(
        "income",
        "Income Verification",
        "Revenue Department",
        "Income Tax Verification",
        "PAN, assessed income FY 2025-26",
        "GET /income/assessment",
        620,
      ),
      stage(
        "education",
        "Education Verification",
        "Education Department",
        "SAMARTH Education API",
        "Enrolment no., marks, institution code",
        "GET /student/{enrolmentNo}",
        980,
        true,
      ),
      stage(
        "bank",
        "Bank Verification",
        "Banking Partners",
        "PFMS Banking Bridge",
        "Account no., IFSC, penny-drop",
        "POST /account/validate",
        430,
      ),
      stage(
        "eligibility",
        "Eligibility Check",
        "GovFlow Rules Engine",
        "Policy Rule Set SCH-2026",
        "Income + marks + category matrix",
        "POST /rules/evaluate",
        160,
      ),
      stage(
        "approval",
        "Department Approval",
        "Education Department",
        "Officer Console",
        "Sanction order draft",
        "POST /approvals",
        540,
      ),
      stage(
        "completed",
        "Completed",
        "GovFlow Portal",
        "DBT Disbursement",
        "Sanction ID, disbursement schedule",
        "POST /dbt/transfer",
        300,
      ),
    ],
  },
  {
    id: "wf-income",
    name: "Income Certificate Issuance",
    serviceId: "income-certificate",
    version: "v2.8",
    status: "Published",
    runs: 2140,
    successRate: 99.1,
    avgMinutes: 4,
    stages: [
      stage(
        "submitted",
        "Application Submitted",
        "GovFlow Portal",
        "Citizen Gateway",
        "Form INC-1",
        "POST /applications",
        190,
      ),
      stage(
        "auth",
        "Authentication",
        "UIDAI",
        "Aadhaar eKYC Gateway",
        "Aadhaar token",
        "POST /ekyc/verify",
        320,
      ),
      stage(
        "consent",
        "Consent Capture",
        "GovFlow Consent Layer",
        "Consent Artefact Registry",
        "Income data scope",
        "POST /consent/artefact",
        160,
      ),
      stage(
        "tax",
        "Tax Record Check",
        "Income Tax Dept.",
        "Income Tax Verification",
        "PAN, ITR summary",
        "GET /itr/summary",
        700,
      ),
      stage(
        "land",
        "Land Holding Check",
        "Revenue Department",
        "Land Records Mainframe",
        "7/12 extract",
        "PULL /712_extract.dat",
        1600,
        true,
      ),
      stage(
        "approval",
        "Tehsildar Approval",
        "Revenue Department",
        "Officer Console",
        "Draft certificate",
        "POST /approvals",
        480,
      ),
      stage(
        "completed",
        "Certificate Issued",
        "GovFlow Portal",
        "DigiLocker",
        "Signed PDF, certificate no.",
        "POST /digilocker/issue",
        260,
      ),
    ],
  },
  {
    id: "wf-residence",
    name: "Residence Certificate Verification",
    serviceId: "residence-certificate",
    version: "v1.9",
    status: "Published",
    runs: 1670,
    successRate: 98.2,
    avgMinutes: 3,
    stages: [
      stage(
        "submitted",
        "Application Submitted",
        "GovFlow Portal",
        "Citizen Gateway",
        "Form RES-1",
        "POST /applications",
        180,
      ),
      stage(
        "auth",
        "Authentication",
        "UIDAI",
        "Aadhaar eKYC Gateway",
        "Aadhaar token",
        "POST /ekyc/verify",
        300,
      ),
      stage(
        "consent",
        "Consent Capture",
        "GovFlow Consent Layer",
        "Consent Artefact Registry",
        "Address data scope",
        "POST /consent/artefact",
        150,
      ),
      stage(
        "property",
        "Property Record Check",
        "Municipal Corporation",
        "Municipal Property SOAP",
        "Property ID, ward, tax status",
        "#getPropertyDetails",
        640,
      ),
      stage(
        "electoral",
        "Electoral Roll Match",
        "Election Commission",
        "Electoral Roll API",
        "EPIC no., part no.",
        "GET /electors",
        420,
      ),
      stage(
        "approval",
        "Ward Officer Approval",
        "Municipal Corporation",
        "Officer Console",
        "Draft certificate",
        "POST /approvals",
        460,
      ),
      stage(
        "completed",
        "Certificate Issued",
        "GovFlow Portal",
        "DigiLocker",
        "Signed PDF",
        "POST /digilocker/issue",
        250,
      ),
    ],
  },
  {
    id: "wf-pension",
    name: "Pension Sanction Orchestration",
    serviceId: "pension",
    version: "v3.1",
    status: "Published",
    runs: 940,
    successRate: 95.4,
    avgMinutes: 9,
    stages: [
      stage(
        "submitted",
        "Application Submitted",
        "GovFlow Portal",
        "Citizen Gateway",
        "Form PEN-1",
        "POST /applications",
        200,
      ),
      stage(
        "auth",
        "Authentication",
        "UIDAI",
        "Aadhaar eKYC Gateway",
        "Aadhaar token",
        "POST /ekyc/verify",
        330,
      ),
      stage(
        "consent",
        "Consent Capture",
        "GovFlow Consent Layer",
        "Consent Artefact Registry",
        "Pension data scope",
        "POST /consent/artefact",
        170,
      ),
      stage(
        "life",
        "Life Certificate",
        "MeitY",
        "Jeevan Pramaan Life Cert.",
        "Pension ID, biometric proof",
        "#getLifeCertificate",
        2400,
        true,
      ),
      stage(
        "income",
        "Income Verification",
        "Revenue Department",
        "Income Tax Verification",
        "Household income",
        "GET /income/assessment",
        640,
      ),
      stage(
        "bank",
        "Bank Verification",
        "Banking Partners",
        "PFMS Banking Bridge",
        "Account validation",
        "POST /account/validate",
        400,
      ),
      stage(
        "approval",
        "Welfare Officer Approval",
        "Social Welfare Department",
        "Officer Console",
        "Sanction order",
        "POST /approvals",
        520,
      ),
      stage(
        "completed",
        "Pension Sanctioned",
        "GovFlow Portal",
        "DBT Disbursement",
        "Monthly DBT schedule",
        "POST /dbt/transfer",
        280,
      ),
    ],
  },
  {
    id: "wf-subsidy",
    name: "Subsidy Enrolment Flow",
    serviceId: "subsidy",
    version: "v2.2",
    status: "Published",
    runs: 1320,
    successRate: 97.3,
    avgMinutes: 5,
    stages: [
      stage(
        "submitted",
        "Application Submitted",
        "GovFlow Portal",
        "Citizen Gateway",
        "Form SUB-1",
        "POST /applications",
        190,
      ),
      stage(
        "auth",
        "Authentication",
        "UIDAI",
        "Aadhaar eKYC Gateway",
        "Aadhaar token",
        "POST /ekyc/verify",
        310,
      ),
      stage(
        "consent",
        "Consent Capture",
        "GovFlow Consent Layer",
        "Consent Artefact Registry",
        "Ration + bank scope",
        "POST /consent/artefact",
        160,
      ),
      stage(
        "ration",
        "Ration Card Match",
        "Food & Civil Supplies",
        "PDS Legacy Mainframe",
        "Ration card master record",
        "PULL /ration_master.dat",
        1750,
        true,
      ),
      stage(
        "bank",
        "Bank Verification",
        "Banking Partners",
        "PFMS Banking Bridge",
        "Account validation",
        "POST /account/validate",
        410,
      ),
      stage(
        "approval",
        "Supply Officer Approval",
        "Food & Civil Supplies",
        "Officer Console",
        "Enrolment order",
        "POST /approvals",
        470,
      ),
      stage(
        "completed",
        "Subsidy Active",
        "GovFlow Portal",
        "DBT Disbursement",
        "Subsidy linkage ID",
        "POST /dbt/transfer",
        260,
      ),
    ],
  },
  {
    id: "wf-business",
    name: "Single-Window Business Registration",
    serviceId: "business-registration",
    version: "v1.4",
    status: "Draft",
    runs: 610,
    successRate: 96.1,
    avgMinutes: 11,
    stages: [
      stage(
        "submitted",
        "Application Submitted",
        "GovFlow Portal",
        "Citizen Gateway",
        "Form BIZ-1",
        "POST /applications",
        210,
      ),
      stage(
        "auth",
        "Authentication",
        "UIDAI",
        "Aadhaar eKYC Gateway",
        "Aadhaar token",
        "POST /ekyc/verify",
        330,
      ),
      stage(
        "consent",
        "Consent Capture",
        "GovFlow Consent Layer",
        "Consent Artefact Registry",
        "Business data scope",
        "POST /consent/artefact",
        170,
      ),
      stage(
        "gst",
        "GST Verification",
        "GST Network",
        "GSTN Taxpayer API",
        "GSTIN, filing status",
        "GET /{gstin}",
        340,
      ),
      stage(
        "property",
        "Premises Verification",
        "Municipal Corporation",
        "Municipal Property SOAP",
        "Property ID, zoning",
        "#getPropertyDetails",
        690,
        true,
      ),
      stage(
        "fire",
        "Fire Safety Clearance",
        "Fire Department",
        "Fire Safety Registry",
        "Inspection report",
        "GET /clearance",
        880,
      ),
      stage(
        "approval",
        "Licence Approval",
        "Municipal Corporation",
        "Officer Console",
        "Trade licence draft",
        "POST /approvals",
        560,
      ),
      stage(
        "completed",
        "Licence Issued",
        "GovFlow Portal",
        "DigiLocker",
        "Licence PDF",
        "POST /digilocker/issue",
        270,
      ),
    ],
  },
  {
    id: "wf-farmer",
    name: "Farmer Assistance Disbursal",
    serviceId: "farmer-assistance",
    version: "v2.0",
    status: "Published",
    runs: 880,
    successRate: 97.8,
    avgMinutes: 7,
    stages: [
      stage(
        "submitted",
        "Application Submitted",
        "GovFlow Portal",
        "Citizen Gateway",
        "Form FRM-1",
        "POST /applications",
        200,
      ),
      stage(
        "auth",
        "Authentication",
        "UIDAI",
        "Aadhaar eKYC Gateway",
        "Aadhaar token",
        "POST /ekyc/verify",
        320,
      ),
      stage(
        "consent",
        "Consent Capture",
        "GovFlow Consent Layer",
        "Consent Artefact Registry",
        "Land + bank scope",
        "POST /consent/artefact",
        160,
      ),
      stage(
        "land",
        "Land Record Check",
        "Revenue Department",
        "Land Records Mainframe",
        "7/12 extract, area",
        "PULL /712_extract.dat",
        1900,
        true,
      ),
      stage(
        "crop",
        "Crop Loss Assessment",
        "Agriculture Department",
        "Agri Market Data Service",
        "Mandi prices, damage index",
        "#getCropPrices",
        540,
      ),
      stage(
        "bank",
        "Bank Verification",
        "Banking Partners",
        "PFMS Banking Bridge",
        "Account validation",
        "POST /account/validate",
        420,
      ),
      stage(
        "approval",
        "Agri Officer Approval",
        "Agriculture Department",
        "Officer Console",
        "Assistance order",
        "POST /approvals",
        500,
      ),
      stage(
        "completed",
        "Assistance Disbursed",
        "GovFlow Portal",
        "DBT Disbursement",
        "Transfer reference",
        "POST /dbt/transfer",
        270,
      ),
    ],
  },
];

export const getWorkflow = (id: string) => WORKFLOWS.find((w) => w.id === id) ?? WORKFLOWS[0]!;
export const getService = (id: string) => SERVICES.find((s) => s.id === id);

/* ----------------------------- applications ------------------------------ */

export type Application = {
  id: string;
  citizen: string;
  citizenId: string;
  serviceId: string;
  locationId: string;
  status: "In Progress" | "Completed" | "Pending" | "Failed";
  stageId: string;
  submitted: string;
  consentIds: string[];
  exceptionIds: string[];
};

const NAMES = [
  "Ramesh Patil",
  "Sunita Sharma",
  "Arjun Nair",
  "Fatima Sheikh",
  "Vikram Reddy",
  "Ananya Iyer",
  "Manoj Kulkarni",
  "Pooja Deshpande",
  "Imran Qureshi",
  "Kavita Joshi",
  "Rahul Verma",
  "Sneha Gaikwad",
  "Suresh Yadav",
  "Lata More",
  "Farhan Khan",
  "Deepa Menon",
  "Ganesh Shinde",
  "Rekha Chavan",
  "Aditya Bhosale",
  "Neha Kapoor",
  "Prakash Jain",
  "Shalini Rao",
  "Yusuf Ansari",
  "Trupti Salunke",
];

const STATUSES: Application["status"][] = [
  "In Progress",
  "Completed",
  "Pending",
  "Failed",
  "Completed",
  "In Progress",
];

export const APPLICATIONS: Application[] = Array.from({ length: 48 }, (_, i) => {
  const service = SERVICES[i % SERVICES.length]!;
  const loc = LOCATIONS[i % LOCATIONS.length]!;
  const wf = getWorkflow(service.workflowId)!;
  const status = i === 0 ? "In Progress" : STATUSES[i % STATUSES.length]!;
  const stageIdx = status === "Completed" ? wf.stages.length - 1 : i % (wf.stages.length - 1) || 1;
  return {
    id: `${service.code}-${10240 + i * 7}`,
    citizen: NAMES[i % NAMES.length]!,
    citizenId: `CIT-${900100 + i * 13}`,
    serviceId: service.id,
    locationId: loc.id,
    status,
    stageId: wf.stages[stageIdx]!.id,
    submitted: `${(i % 27) + 1} Sep 2026`,
    consentIds: [`CA-2026-${70000 + i * 3}`],
    exceptionIds: status === "Failed" ? [`EXC-${4400 + i}`] : [],
  };
});

// Hero demo application
APPLICATIONS[0] = {
  id: "SCH-10291",
  citizen: "Ramesh Patil",
  citizenId: "CIT-900100",
  serviceId: "scholarship",
  locationId: "nashik",
  status: "In Progress",
  stageId: "education",
  submitted: "12 Sep 2026",
  consentIds: ["CA-2026-77431", "CA-2026-77432"],
  exceptionIds: ["EXC-4401"],
};

/* -------------------------------- consent -------------------------------- */

export type Consent = {
  id: string;
  applicationId: string;
  requestedBy: string;
  dataRequested: string;
  purpose: string;
  recipient: string;
  status: "Active" | "Pending" | "Expired" | "Revoked";
  grantedOn: string;
  expiry: string;
};

export const CONSENTS: Consent[] = [
  {
    id: "CA-2026-77431",
    applicationId: "SCH-10291",
    requestedBy: "Education Department",
    dataRequested: "Enrolment record, marks, institution",
    purpose: "Verify academic eligibility for post-matric scholarship",
    recipient: "SAMARTH Education API",
    status: "Active",
    grantedOn: "12 Sep 2026",
    expiry: "12 Dec 2026",
  },
  {
    id: "CA-2026-77432",
    applicationId: "SCH-10291",
    requestedBy: "Revenue Department",
    dataRequested: "Assessed family income FY 2025-26",
    purpose: "Means test for scholarship income ceiling",
    recipient: "Income Tax Verification",
    status: "Active",
    grantedOn: "12 Sep 2026",
    expiry: "12 Dec 2026",
  },
  {
    id: "CA-2026-77433",
    applicationId: "SCH-10291",
    requestedBy: "Banking Partners",
    dataRequested: "Bank account holder name, IFSC",
    purpose: "Direct benefit transfer account validation",
    recipient: "PFMS Banking Bridge",
    status: "Pending",
    grantedOn: "—",
    expiry: "—",
  },
  {
    id: "CA-2026-77410",
    applicationId: "INC-10247",
    requestedBy: "Revenue Department",
    dataRequested: "ITR summary, PAN",
    purpose: "Income certificate issuance",
    recipient: "Income Tax Verification",
    status: "Active",
    grantedOn: "08 Sep 2026",
    expiry: "08 Nov 2026",
  },
  {
    id: "CA-2026-77388",
    applicationId: "PEN-10275",
    requestedBy: "Social Welfare Department",
    dataRequested: "Life certificate, biometric status",
    purpose: "Pension continuation verification",
    recipient: "Jeevan Pramaan",
    status: "Expired",
    grantedOn: "02 Jun 2026",
    expiry: "02 Sep 2026",
  },
  {
    id: "CA-2026-77366",
    applicationId: "SUB-10268",
    requestedBy: "Food & Civil Supplies",
    dataRequested: "Ration card household data",
    purpose: "Subsidy enrolment eligibility",
    recipient: "PDS Legacy Mainframe",
    status: "Revoked",
    grantedOn: "21 Aug 2026",
    expiry: "21 Nov 2026",
  },
  {
    id: "CA-2026-77350",
    applicationId: "FRM-10282",
    requestedBy: "Agriculture Department",
    dataRequested: "7/12 land extract, crop pattern",
    purpose: "Crop-loss assistance assessment",
    recipient: "Land Records Mainframe",
    status: "Active",
    grantedOn: "18 Aug 2026",
    expiry: "18 Feb 2027",
  },
];

/* ------------------------------ exceptions ------------------------------- */

export type ExceptionItem = {
  id: string;
  applicationId: string;
  stage: string;
  system: string;
  code: string;
  message: string;
  severity: "Critical" | "High" | "Medium";
  detectedAt: string;
  attempts: number;
  status: "Open" | "Recovered" | "Escalated";
  recovery: string;
};

export const EXCEPTIONS: ExceptionItem[] = [
  {
    id: "EXC-4401",
    applicationId: "SCH-10291",
    stage: "Education Verification",
    system: "SAMARTH Education API",
    code: "HTTP 504",
    message: "Upstream gateway timeout while fetching enrolment record",
    severity: "High",
    detectedAt: "12 Sep 2026, 10:42",
    attempts: 1,
    status: "Open",
    recovery: "Exponential backoff retry (3 attempts) then failover to state education mirror",
  },
  {
    id: "EXC-4402",
    applicationId: "PEN-10275",
    stage: "Life Certificate",
    system: "Jeevan Pramaan",
    code: "SOAP Fault",
    message: "Upstream biometric service unavailable",
    severity: "Critical",
    detectedAt: "11 Sep 2026, 16:08",
    attempts: 3,
    status: "Escalated",
    recovery: "Manual officer override with physical life certificate",
  },
  {
    id: "EXC-4403",
    applicationId: "SUB-10268",
    stage: "Ration Card Match",
    system: "PDS Legacy Mainframe",
    code: "PARSE_ERR",
    message: "Fixed-width record length mismatch in ration_master.dat",
    severity: "Medium",
    detectedAt: "11 Sep 2026, 09:21",
    attempts: 2,
    status: "Recovered",
    recovery: "Schema mapper fallback to v2 layout, re-parsed successfully",
  },
  {
    id: "EXC-4404",
    applicationId: "FRM-10282",
    stage: "Land Record Check",
    system: "Land Records Mainframe",
    code: "SFTP_TIMEOUT",
    message: "Batch pull exceeded 30s window",
    severity: "High",
    detectedAt: "10 Sep 2026, 22:55",
    attempts: 1,
    status: "Open",
    recovery: "Queue for next batch window with incremental cursor",
  },
  {
    id: "EXC-4405",
    applicationId: "BIZ-10254",
    stage: "Premises Verification",
    system: "Municipal Property SOAP",
    code: "WS-SEC 401",
    message: "UsernameToken expired for ULB endpoint",
    severity: "Medium",
    detectedAt: "10 Sep 2026, 14:12",
    attempts: 1,
    status: "Recovered",
    recovery: "Credential rotation applied, request replayed",
  },
  {
    id: "EXC-4406",
    applicationId: "INC-10247",
    stage: "Land Holding Check",
    system: "Land Records Mainframe",
    code: "HTTP 502",
    message: "Legacy adapter returned malformed response",
    severity: "Medium",
    detectedAt: "09 Sep 2026, 11:33",
    attempts: 2,
    status: "Open",
    recovery: "Normalize via legacy adapter v3 and retry",
  },
];

/* ------------------------------ audit logs ------------------------------- */

export type AuditEntry = {
  id: string;
  time: string;
  actor: string;
  action: string;
  entity: string;
  type: "Workflow" | "Data Access" | "Consent" | "API Call" | "Status Change" | "Auth";
  result: "Success" | "Failure";
  ip: string;
};

const AUDIT_SEED: [string, string, string, AuditEntry["type"], AuditEntry["result"]][] = [
  [
    "System Orchestrator",
    "Workflow stage advanced to Education Verification",
    "SCH-10291",
    "Workflow",
    "Success",
  ],
  [
    "SAMARTH Education API",
    "GET /student/MH-NSK-2024-88213 returned 504",
    "SCH-10291",
    "API Call",
    "Failure",
  ],
  [
    "System Orchestrator",
    "Automatic retry scheduled (attempt 2)",
    "EXC-4401",
    "Workflow",
    "Success",
  ],
  ["Ramesh Patil", "Consent granted for income data", "CA-2026-77432", "Consent", "Success"],
  ["Revenue Department", "Accessed assessed income record", "CIT-900100", "Data Access", "Success"],
  ["Anjali Deshmukh", "Approved income certificate", "INC-10247", "Status Change", "Success"],
  ["Developer Console", "Rotated WS-Security credentials", "int-municipal", "API Call", "Success"],
  ["Ramesh Patil", "Signed in with mobile OTP", "CIT-900100", "Auth", "Success"],
  ["Social Welfare Dept.", "Life certificate fetch failed", "PEN-10275", "API Call", "Failure"],
  ["Sunita Sharma", "Consent revoked for ration data", "CA-2026-77366", "Consent", "Success"],
  [
    "System Orchestrator",
    "Schema mapping v3 applied to legacy payload",
    "int-pds",
    "Data Access",
    "Success",
  ],
  [
    "Rajesh Kulkarni",
    "Escalated exception to nodal officer",
    "EXC-4402",
    "Status Change",
    "Success",
  ],
];

export const AUDIT_LOGS: AuditEntry[] = Array.from({ length: 36 }, (_, i) => {
  const [actor, action, entity, type, result] = AUDIT_SEED[i % AUDIT_SEED.length]!;
  const h = 23 - Math.floor(i / 2);
  return {
    id: `AUD-${88000 + i * 5}`,
    time: `12 Sep 2026, ${String(Math.max(h, 0)).padStart(2, "0")}:${String((i * 7) % 60).padStart(2, "0")}`,
    actor,
    action,
    entity,
    type,
    result,
    ip: `10.${(i % 9) + 1}.24.${(i * 11) % 250}`,
  };
});

/* --------------------------------- users --------------------------------- */

export type PlatformUser = {
  id: string;
  name: string;
  email: string;
  role: Role;
  department: string;
  locationId: string;
  status: "Active" | "Suspended";
  lastActive: string;
};

export const USERS: PlatformUser[] = [
  {
    id: "USR-001",
    name: "Ramesh Patil",
    email: "ramesh.patil@gov.in",
    role: "Department Officer",
    department: "Education Department",
    locationId: "nashik",
    status: "Active",
    lastActive: "2 mins ago",
  },
  {
    id: "USR-002",
    name: "Anjali Deshmukh",
    email: "anjali.d@gov.in",
    role: "Admin",
    department: "Revenue Department",
    locationId: "pune",
    status: "Active",
    lastActive: "18 mins ago",
  },
  {
    id: "USR-003",
    name: "Nikhil Rane",
    email: "nikhil.rane@gov.in",
    role: "Developer",
    department: "GovFlow Platform",
    locationId: "mumbai",
    status: "Active",
    lastActive: "1 hour ago",
  },
  {
    id: "USR-004",
    name: "Sadhana Rao",
    email: "sadhana.rao@gov.in",
    role: "Auditor",
    department: "CAG Cell",
    locationId: "delhi",
    status: "Active",
    lastActive: "3 hours ago",
  },
  {
    id: "USR-005",
    name: "Imran Qureshi",
    email: "imran.q@gov.in",
    role: "Operator",
    department: "Social Welfare Department",
    locationId: "hyderabad",
    status: "Suspended",
    lastActive: "2 days ago",
  },
  {
    id: "USR-006",
    name: "Divya Menon",
    email: "divya.menon@gov.in",
    role: "Department Officer",
    department: "Agriculture Department",
    locationId: "bengaluru",
    status: "Active",
    lastActive: "26 mins ago",
  },
  {
    id: "USR-007",
    name: "Sandeep More",
    email: "sandeep.more@gov.in",
    role: "Department Officer",
    department: "Municipal Corporation",
    locationId: "nashik",
    status: "Active",
    lastActive: "44 mins ago",
  },
  {
    id: "USR-008",
    name: "Kiran Bhatt",
    email: "kiran.bhatt@gov.in",
    role: "Developer",
    department: "GovFlow Platform",
    locationId: "pune",
    status: "Active",
    lastActive: "5 hours ago",
  },
];

/* ----------------------------- data mapping ------------------------------ */

export type FieldMap = {
  id: string;
  source: string;
  sourceType: string;
  target: string;
  targetType: string;
  transform: string;
  confidence: number;
  status: "Mapped" | "Unmapped" | "Review";
};

export const MAPPING_PRESETS: Record<string, FieldMap[]> = {
  "int-aadhaar": [
    {
      id: "sih-annual-income",
      source: "annualIncome",
      sourceType: "number",
      target: "familyIncome",
      targetType: "currency",
      transform: "normalizeINR",
      confidence: 91,
      status: "Review",
    },
    {
      id: "sih-aadhaar-number",
      source: "aadhaarNumber",
      sourceType: "string",
      target: "citizenId",
      targetType: "token",
      transform: "sha256 + mask",
      confidence: 96,
      status: "Mapped",
    },
    {
      id: "sih-district-code",
      source: "districtCode",
      sourceType: "string",
      target: "jurisdictionCode",
      targetType: "string",
      transform: "lookupDistrict",
      confidence: 89,
      status: "Review",
    },
    {
      id: "m1",
      source: "citizen_name",
      sourceType: "string",
      target: "fullName",
      targetType: "string",
      transform: "trim + titleCase",
      confidence: 98,
      status: "Mapped",
    },
    {
      id: "m2",
      source: "mobile_no",
      sourceType: "string",
      target: "phone",
      targetType: "E.164",
      transform: "normalizePhone(+91)",
      confidence: 96,
      status: "Mapped",
    },
    {
      id: "m3",
      source: "dob",
      sourceType: "dd-mm-yyyy",
      target: "dateOfBirth",
      targetType: "ISO-8601",
      transform: "parseDate",
      confidence: 99,
      status: "Mapped",
    },
    {
      id: "m4",
      source: "address.district",
      sourceType: "string",
      target: "location.district",
      targetType: "string",
      transform: "direct",
      confidence: 92,
      status: "Mapped",
    },
    {
      id: "m5",
      source: "uid",
      sourceType: "string",
      target: "citizenRef",
      targetType: "hash",
      transform: "sha256 + mask",
      confidence: 88,
      status: "Review",
    },
  ],
  "int-municipal": [
    {
      id: "m1",
      source: "OwnerName",
      sourceType: "xs:string",
      target: "fullName",
      targetType: "string",
      transform: "titleCase",
      confidence: 94,
      status: "Mapped",
    },
    {
      id: "m2",
      source: "Ward",
      sourceType: "xs:string",
      target: "location.ward",
      targetType: "string",
      transform: "direct",
      confidence: 90,
      status: "Mapped",
    },
    {
      id: "m3",
      source: "TaxStatus",
      sourceType: "xs:enum",
      target: "taxCompliant",
      targetType: "boolean",
      transform: "PAID → true",
      confidence: 86,
      status: "Review",
    },
    {
      id: "m4",
      source: "propertyId",
      sourceType: "xs:string",
      target: "premisesRef",
      targetType: "string",
      transform: "direct",
      confidence: 97,
      status: "Mapped",
    },
  ],
  "int-pds": [
    {
      id: "m1",
      source: "HEAD",
      sourceType: "fixed(40)",
      target: "fullName",
      targetType: "string",
      transform: "rtrim + reorderName",
      confidence: 82,
      status: "Review",
    },
    {
      id: "m2",
      source: "RC",
      sourceType: "fixed(12)",
      target: "rationCardNo",
      targetType: "string",
      transform: "rtrim",
      confidence: 95,
      status: "Mapped",
    },
    {
      id: "m3",
      source: "MEMBERS",
      sourceType: "fixed(2)",
      target: "householdSize",
      targetType: "number",
      transform: "parseInt",
      confidence: 91,
      status: "Mapped",
    },
    {
      id: "m4",
      source: "TYPE",
      sourceType: "fixed(3)",
      target: "rationCategory",
      targetType: "enum",
      transform: "APL|BPL map",
      confidence: 78,
      status: "Unmapped",
    },
  ],
  "int-samarth": [
    {
      id: "m1",
      source: "student_full_name",
      sourceType: "string",
      target: "fullName",
      targetType: "string",
      transform: "titleCase",
      confidence: 97,
      status: "Mapped",
    },
    {
      id: "m2",
      source: "institution",
      sourceType: "string",
      target: "instituteName",
      targetType: "string",
      transform: "direct",
      confidence: 93,
      status: "Mapped",
    },
    {
      id: "m3",
      source: "percentage",
      sourceType: "number",
      target: "academicScore",
      targetType: "number",
      transform: "round(2)",
      confidence: 99,
      status: "Mapped",
    },
    {
      id: "m4",
      source: "enrolmentNo",
      sourceType: "string",
      target: "enrolmentRef",
      targetType: "string",
      transform: "upper",
      confidence: 94,
      status: "Mapped",
    },
  ],
  "int-pfms": [
    {
      id: "sih-account-number",
      source: "accountNumber",
      sourceType: "string",
      target: "bankAccount",
      targetType: "masked-string",
      transform: "mask + validateIFSC",
      confidence: 95,
      status: "Mapped",
    },
  ],
};

/* ------------------------- SIH intelligence views ------------------------ */

export type LineageEvent = {
  id: string;
  source: string;
  destination: string;
  timestamp: string;
  api: string;
  fields: string[];
  consentRef: string;
  transformation: string;
};

export const LINEAGE_EVENTS: LineageEvent[] = [
  {
    id: "lin-1",
    source: "Citizen Gateway",
    destination: "Education Department",
    timestamp: "12 Sep 2026, 10:41:02",
    api: "POST /applications",
    fields: ["citizenId", "serviceCode", "institutionRef"],
    consentRef: "CA-2026-77431",
    transformation: "Normalize form payload to canonical application",
  },
  {
    id: "lin-2",
    source: "Education Department",
    destination: "SAMARTH Education API",
    timestamp: "12 Sep 2026, 10:41:05",
    api: "GET /student/{enrolmentNo}",
    fields: ["enrolmentRef", "academicYear"],
    consentRef: "CA-2026-77431",
    transformation: "Map enrolmentRef to enrolmentNo",
  },
  {
    id: "lin-3",
    source: "SAMARTH Education API",
    destination: "GovFlow Normalization",
    timestamp: "12 Sep 2026, 10:42:11",
    api: "POST /normalize/education",
    fields: ["student_full_name", "percentage", "status"],
    consentRef: "CA-2026-77431",
    transformation: "student_full_name -> fullName; percentage -> academicScore",
  },
  {
    id: "lin-4",
    source: "GovFlow Normalization",
    destination: "PFMS Banking Bridge",
    timestamp: "12 Sep 2026, 10:42:17",
    api: "POST /account/validate",
    fields: ["bankAccount", "ifsc", "citizenId"],
    consentRef: "CA-2026-77433",
    transformation: "Mask account number and attach consent artefact",
  },
];

export type DependencyNode = {
  id: string;
  name: string;
  kind: "GovFlow" | "Department" | "System";
  health: Health;
  latencyMs: number;
  failures24h: number;
  x: number;
  y: number;
};

export const DEPENDENCY_NODES: DependencyNode[] = [
  {
    id: "govflow",
    name: "GovFlow",
    kind: "GovFlow",
    health: "Healthy",
    latencyMs: 42,
    failures24h: 0,
    x: 50,
    y: 50,
  },
  {
    id: "aadhaar",
    name: "Aadhaar",
    kind: "System",
    health: "Healthy",
    latencyMs: 240,
    failures24h: 3,
    x: 16,
    y: 18,
  },
  {
    id: "revenue",
    name: "Revenue",
    kind: "Department",
    health: "Healthy",
    latencyMs: 320,
    failures24h: 6,
    x: 84,
    y: 18,
  },
  {
    id: "education",
    name: "Education",
    kind: "Department",
    health: "Degraded",
    latencyMs: 980,
    failures24h: 41,
    x: 15,
    y: 82,
  },
  {
    id: "pfms",
    name: "PFMS",
    kind: "System",
    health: "Healthy",
    latencyMs: 380,
    failures24h: 7,
    x: 85,
    y: 82,
  },
  {
    id: "land",
    name: "Land Records",
    kind: "System",
    health: "Degraded",
    latencyMs: 2100,
    failures24h: 58,
    x: 50,
    y: 12,
  },
  {
    id: "municipal",
    name: "Municipal",
    kind: "Department",
    health: "Healthy",
    latencyMs: 640,
    failures24h: 12,
    x: 50,
    y: 88,
  },
];

export const DEPENDENCY_EDGES: [string, string][] = [
  ["govflow", "aadhaar"],
  ["govflow", "revenue"],
  ["govflow", "education"],
  ["govflow", "pfms"],
  ["govflow", "land"],
  ["govflow", "municipal"],
  ["education", "land"],
  ["revenue", "land"],
];

export type Bottleneck = {
  stage: string;
  workflow: string;
  impact: "High" | "Medium";
  latency: string;
  failureRate: string;
  recommendation: string;
};

export const BOTTLENECKS: Bottleneck[] = [
  {
    stage: "Education Verification",
    workflow: "Scholarship Application",
    impact: "High",
    latency: "980 ms",
    failureRate: "5.8%",
    recommendation: "Route timeouts to the state education mirror after retry 2/3.",
  },
  {
    stage: "Land Record Check",
    workflow: "Farmer Assistance",
    impact: "High",
    latency: "2.1 s",
    failureRate: "8.3%",
    recommendation:
      "Pre-fetch the nightly extract and validate fixed-width records before orchestration.",
  },
  {
    stage: "Life Certificate",
    workflow: "Pension Sanction",
    impact: "High",
    latency: "4.2 s",
    failureRate: "37.6%",
    recommendation: "Use manual officer override when biometric availability is below 90%.",
  },
  {
    stage: "Premises Verification",
    workflow: "Business Registration",
    impact: "Medium",
    latency: "640 ms",
    failureRate: "1.7%",
    recommendation: "Cache property tax status for the current assessment cycle.",
  },
];

export const IMPACT_METRICS = [
  { label: "Steps", before: "18 manual steps", after: "8 orchestrated stages" },
  { label: "Systems involved", before: "6 disconnected portals", after: "1 governed graph" },
  { label: "Manual handoffs", before: "9 handoffs", after: "0 handoffs" },
  { label: "Completion time", before: "14–21 days", after: "6 minutes average" },
];

/* ------------------------------ notifications ---------------------------- */

export type Notification = {
  id: string;
  title: string;
  body: string;
  kind: "Workflow" | "API" | "Consent" | "Application" | "System";
  time: string;
  read: boolean;
};

export const NOTIFICATIONS: Notification[] = [
  {
    id: "n1",
    title: "Education verification retrying",
    body: "SCH-10291 · SAMARTH API returned 504, automatic retry in progress",
    kind: "API",
    time: "2 mins ago",
    read: false,
  },
  {
    id: "n2",
    title: "Consent granted",
    body: "CA-2026-77432 · Income data shared with Revenue Department",
    kind: "Consent",
    time: "12 mins ago",
    read: false,
  },
  {
    id: "n3",
    title: "Workflow completed",
    body: "INC-10247 · Income Certificate issued to Sunita Sharma",
    kind: "Workflow",
    time: "28 mins ago",
    read: false,
  },
  {
    id: "n4",
    title: "New application received",
    body: "FRM-10282 · Farmer Assistance from Ozar, Nashik",
    kind: "Application",
    time: "42 mins ago",
    read: true,
  },
  {
    id: "n5",
    title: "System degraded",
    body: "Jeevan Pramaan life certificate service is down (88.3% uptime)",
    kind: "System",
    time: "1 hour ago",
    read: true,
  },
  {
    id: "n6",
    title: "Integration added",
    body: "Agri Market Data Service connected to Agriculture Department",
    kind: "System",
    time: "3 hours ago",
    read: true,
  },
];

/* -------------------------------- charts --------------------------------- */

export const MONTHS = ["Apr", "May", "Jun", "Jul", "Aug", "Sep"];

export const applicationSeries = (load: number) =>
  MONTHS.map((m, i) => ({
    month: m,
    completed: Math.round((80 + i * 16) * load),
    inProgress: Math.round((55 + i * 9) * load),
    pending: Math.round((28 + (i % 3) * 6) * load),
    failed: Math.round((12 - i) * load + 4),
  }));

export const latencySeries = (load: number) =>
  Array.from({ length: 12 }, (_, i) => ({
    t: `${String(i * 2).padStart(2, "0")}:00`,
    latency: Math.round(280 + Math.sin(i / 1.7) * 120 + load * 40),
    success: Math.round(96 + Math.cos(i / 2.2) * 2.2),
  }));

export const departmentPerf = (load: number) =>
  DEPARTMENTS.map((d) => ({
    name: d.name.replace(" Department", "").replace(" Partners (PFMS)", ""),
    processed: Math.round((120 + d.uptime) * load),
    avgHours: Math.round(d.responseMs / 60) / 2 + 8,
  }));
