"""create interoperability database foundation

Revision ID: c658ed35c11a
Revises: 
Create Date: 2026-09-28 19:34:12.256222

"""
from typing import Sequence, Union
import uuid

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c658ed35c11a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_departments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_departments_public_id'), ['public_id'], unique=True)

    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('name')
    )
    op.bulk_insert(
        sa.table(
            "roles",
            sa.column("id", sa.Uuid()),
            sa.column("key", sa.String()),
            sa.column("name", sa.String()),
            sa.column("description", sa.String()),
        ),
        [
            {
                "id": uuid.UUID("27d7f037-208e-4e9f-8df9-28c73cc44001"),
                "key": "citizen",
                "name": "Citizen",
                "description": "Public service applicant and data subject.",
            },
            {
                "id": uuid.UUID("27d7f037-208e-4e9f-8df9-28c73cc44002"),
                "key": "officer",
                "name": "Government Officer",
                "description": "Department officer processing assigned applications.",
            },
            {
                "id": uuid.UUID("27d7f037-208e-4e9f-8df9-28c73cc44003"),
                "key": "admin",
                "name": "Administrator",
                "description": "Platform administrator.",
            },
            {
                "id": uuid.UUID("27d7f037-208e-4e9f-8df9-28c73cc44004"),
                "key": "developer",
                "name": "Developer",
                "description": "Integration and service developer.",
            },
            {
                "id": uuid.UUID("27d7f037-208e-4e9f-8df9-28c73cc44005"),
                "key": "operator",
                "name": "Operator",
                "description": "Platform operations staff.",
            },
            {
                "id": uuid.UUID("27d7f037-208e-4e9f-8df9-28c73cc44006"),
                "key": "auditor",
                "name": "Auditor",
                "description": "Read-only compliance auditor.",
            },
        ],
    )
    op.create_table('connected_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('api_version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DEGRADED', 'OFFLINE', name='platformstatus'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('integration_type', sa.String(length=40), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('connected_systems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connected_systems_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_connected_systems_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_connected_systems_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_connected_systems_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('aadhaar_last4', sa.String(length=4), nullable=True),
    sa.Column('role', sa.Enum('CITIZEN', 'OFFICER', 'ADMIN', 'DEVELOPER', 'OPERATOR', 'AUDITOR', name='userrole'), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role_id'), ['role_id'], unique=False)

    op.create_table('data_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('integration_id', sa.Integer(), nullable=True),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('target_system_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('source_schema_version', sa.String(length=40), nullable=False),
    sa.Column('target_schema_version', sa.String(length=40), nullable=False),
    sa.Column('source', sa.String(length=160), nullable=False),
    sa.Column('target', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['connected_systems.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_system_id'], ['connected_systems.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_system_id'], ['connected_systems.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system_id', 'target_system_id', 'name', 'version', name='uq_data_mapping_system_pair_version')
    )
    with op.batch_alter_table('data_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_mappings_integration_id'), ['integration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_mappings_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_data_mappings_source_system_id'), ['source_system_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_mappings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_mappings_target_system_id'), ['target_system_id'], unique=False)

    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['platform_id'], ['connected_systems.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_services_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_platform_id'), ['platform_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_public_id'), ['public_id'], unique=True)

    op.create_table('data_mapping_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mapping_id', sa.Integer(), nullable=False),
    sa.Column('source_field', sa.String(length=160), nullable=False),
    sa.Column('target_field', sa.String(length=160), nullable=False),
    sa.Column('transformation', sa.Text(), nullable=True),
    sa.Column('validation_expression', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['mapping_id'], ['data_mappings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mapping_id', 'source_field', 'target_field', name='uq_data_mapping_field_pair')
    )
    with op.batch_alter_table('data_mapping_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_mapping_rules_mapping_id'), ['mapping_id'], unique=False)

    op.create_table('service_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', name='applicationstatus'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('citizen_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('form_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_applications_citizen_id'), ['citizen_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_applications_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_applications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_applications_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_service_applications_reference_id'), ['reference_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_service_applications_service_id'), ['service_id'], unique=False)

    op.create_table('application_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['application_id'], ['service_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_events_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_events_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_events_status'), ['status'], unique=False)

    op.create_table('data_share_consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'GRANTED', 'ACTIVE', 'DENIED', 'REVOKED', 'EXPIRED', name='consentstatus'), nullable=False),
    sa.Column('source_platform_id', sa.Integer(), nullable=False),
    sa.Column('target_platform_id', sa.Integer(), nullable=False),
    sa.Column('citizen_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('requesting_department_id', sa.Integer(), nullable=False),
    sa.Column('source_department_id', sa.Integer(), nullable=False),
    sa.Column('requested_data', sa.Text(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['service_applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['citizen_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requesting_department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_platform_id'], ['connected_systems.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_platform_id'], ['connected_systems.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_share_consents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_share_consents_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_share_consents_citizen_id'), ['citizen_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_share_consents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_share_consents_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_data_share_consents_requesting_department_id'), ['requesting_department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_share_consents_source_department_id'), ['source_department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_share_consents_source_platform_id'), ['source_platform_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_share_consents_target_platform_id'), ['target_platform_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('doc_type', sa.String(length=80), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_score', sa.Float(), nullable=True),
    sa.Column('fraud_risk_level', sa.String(length=30), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extracted_entities', sa.JSON(), nullable=True),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['service_applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_public_id'), ['public_id'], unique=True)

    op.create_table('government_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('citizen_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('connected_system_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('record_type', sa.String(length=100), nullable=False),
    sa.Column('source_record_id', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('schema_version', sa.String(length=40), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['service_applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['citizen_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['connected_system_id'], ['connected_systems.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('government_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_government_records_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_government_records_citizen_id'), ['citizen_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_government_records_connected_system_id'), ['connected_system_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_government_records_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_government_records_record_type'), ['record_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_government_records_status'), ['status'], unique=False)

    op.create_table('workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['service_applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflows_application_id'), ['application_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_workflows_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_workflows_service_id'), ['service_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflows_status'), ['status'], unique=False)

    op.create_table('consent_data_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consent_id', sa.Integer(), nullable=False),
    sa.Column('data_key', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('classification', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['consent_id'], ['data_share_consents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consent_data_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consent_data_items_consent_id'), ['consent_id'], unique=False)

    op.create_table('government_record_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Uuid(), nullable=False),
    sa.Column('field_key', sa.String(length=120), nullable=False),
    sa.Column('field_value', sa.String(length=4000), nullable=False),
    sa.Column('data_type', sa.String(length=32), nullable=False),
    sa.Column('classification', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['government_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('government_record_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_government_record_values_record_id'), ['record_id'], unique=False)

    op.create_table('interoperability_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=80), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('citizen_id', sa.Integer(), nullable=False),
    sa.Column('consent_id', sa.Integer(), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('destination_system_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('requesting_department', sa.String(length=200), nullable=False),
    sa.Column('source_department', sa.String(length=200), nullable=False),
    sa.Column('data_requested', sa.String(length=500), nullable=False),
    sa.Column('purpose', sa.String(length=500), nullable=False),
    sa.Column('consent_status', sa.String(length=40), nullable=False),
    sa.Column('request_status', sa.String(length=40), nullable=False),
    sa.Column('validation_status', sa.String(length=40), nullable=False),
    sa.Column('mapping_status', sa.String(length=40), nullable=False),
    sa.Column('response_status', sa.String(length=40), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['service_applications.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['citizen_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['consent_id'], ['data_share_consents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['destination_system_id'], ['connected_systems.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_system_id'], ['connected_systems.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interoperability_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interoperability_transactions_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interoperability_transactions_citizen_id'), ['citizen_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interoperability_transactions_consent_id'), ['consent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interoperability_transactions_destination_system_id'), ['destination_system_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interoperability_transactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interoperability_transactions_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_interoperability_transactions_requested_at'), ['requested_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_interoperability_transactions_source_system_id'), ['source_system_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interoperability_transactions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_interoperability_transactions_transaction_id'), ['transaction_id'], unique=True)

    op.create_table('workflow_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('connected_system_id', sa.Integer(), nullable=True),
    sa.Column('step_key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['connected_system_id'], ['connected_systems.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_steps_connected_system_id'), ['connected_system_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_steps_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_steps_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Uuid(), nullable=True),
    sa.Column('actor_role', sa.String(length=32), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('resource', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(length=80), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['interoperability_transactions.public_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_audit_logs_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('interoperability_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.String(length=80), nullable=True),
    sa.Column('service_application_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('connected_system_id', sa.Integer(), nullable=True),
    sa.Column('system', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'ESCALATED', name='exceptionstatus'), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['connected_system_id'], ['connected_systems.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_application_id'], ['service_applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['interoperability_transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interoperability_exceptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interoperability_exceptions_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interoperability_exceptions_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_interoperability_exceptions_connected_system_id'), ['connected_system_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interoperability_exceptions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interoperability_exceptions_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_interoperability_exceptions_service_application_id'), ['service_application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interoperability_exceptions_system'), ['system'], unique=False)
        batch_op.create_index(batch_op.f('ix_interoperability_exceptions_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('notification_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['service_applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['interoperability_transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_notifications_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('transaction_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['interoperability_transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_events_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_events_transaction_id'), ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_events_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_events_status'))
        batch_op.drop_index(batch_op.f('ix_transaction_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_transaction_events_event_type'))

    op.drop_table('transaction_events')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_status'))
        batch_op.drop_index(batch_op.f('ix_notifications_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_public_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_application_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('interoperability_exceptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interoperability_exceptions_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_interoperability_exceptions_system'))
        batch_op.drop_index(batch_op.f('ix_interoperability_exceptions_service_application_id'))
        batch_op.drop_index(batch_op.f('ix_interoperability_exceptions_public_id'))
        batch_op.drop_index(batch_op.f('ix_interoperability_exceptions_id'))
        batch_op.drop_index(batch_op.f('ix_interoperability_exceptions_connected_system_id'))
        batch_op.drop_index(batch_op.f('ix_interoperability_exceptions_category'))
        batch_op.drop_index(batch_op.f('ix_interoperability_exceptions_application_id'))

    op.drop_table('interoperability_exceptions')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_role_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_public_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_department_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('workflow_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_steps_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_steps_status'))
        batch_op.drop_index(batch_op.f('ix_workflow_steps_connected_system_id'))

    op.drop_table('workflow_steps')
    with op.batch_alter_table('interoperability_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interoperability_transactions_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_interoperability_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_interoperability_transactions_source_system_id'))
        batch_op.drop_index(batch_op.f('ix_interoperability_transactions_requested_at'))
        batch_op.drop_index(batch_op.f('ix_interoperability_transactions_public_id'))
        batch_op.drop_index(batch_op.f('ix_interoperability_transactions_id'))
        batch_op.drop_index(batch_op.f('ix_interoperability_transactions_destination_system_id'))
        batch_op.drop_index(batch_op.f('ix_interoperability_transactions_consent_id'))
        batch_op.drop_index(batch_op.f('ix_interoperability_transactions_citizen_id'))
        batch_op.drop_index(batch_op.f('ix_interoperability_transactions_application_id'))

    op.drop_table('interoperability_transactions')
    with op.batch_alter_table('government_record_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_government_record_values_record_id'))

    op.drop_table('government_record_values')
    with op.batch_alter_table('consent_data_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consent_data_items_consent_id'))

    op.drop_table('consent_data_items')
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflows_status'))
        batch_op.drop_index(batch_op.f('ix_workflows_service_id'))
        batch_op.drop_index(batch_op.f('ix_workflows_public_id'))
        batch_op.drop_index(batch_op.f('ix_workflows_application_id'))

    op.drop_table('workflows')
    with op.batch_alter_table('government_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_government_records_status'))
        batch_op.drop_index(batch_op.f('ix_government_records_record_type'))
        batch_op.drop_index(batch_op.f('ix_government_records_department_id'))
        batch_op.drop_index(batch_op.f('ix_government_records_connected_system_id'))
        batch_op.drop_index(batch_op.f('ix_government_records_citizen_id'))
        batch_op.drop_index(batch_op.f('ix_government_records_application_id'))

    op.drop_table('government_records')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_public_id'))
        batch_op.drop_index(batch_op.f('ix_documents_owner_id'))
        batch_op.drop_index(batch_op.f('ix_documents_id'))
        batch_op.drop_index(batch_op.f('ix_documents_application_id'))

    op.drop_table('documents')
    with op.batch_alter_table('data_share_consents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_share_consents_target_platform_id'))
        batch_op.drop_index(batch_op.f('ix_data_share_consents_source_platform_id'))
        batch_op.drop_index(batch_op.f('ix_data_share_consents_source_department_id'))
        batch_op.drop_index(batch_op.f('ix_data_share_consents_requesting_department_id'))
        batch_op.drop_index(batch_op.f('ix_data_share_consents_public_id'))
        batch_op.drop_index(batch_op.f('ix_data_share_consents_id'))
        batch_op.drop_index(batch_op.f('ix_data_share_consents_citizen_id'))
        batch_op.drop_index(batch_op.f('ix_data_share_consents_application_id'))

    op.drop_table('data_share_consents')
    with op.batch_alter_table('application_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_events_status'))
        batch_op.drop_index(batch_op.f('ix_application_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_application_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_application_events_application_id'))
        batch_op.drop_index(batch_op.f('ix_application_events_actor_id'))

    op.drop_table('application_events')
    with op.batch_alter_table('service_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_applications_service_id'))
        batch_op.drop_index(batch_op.f('ix_service_applications_reference_id'))
        batch_op.drop_index(batch_op.f('ix_service_applications_public_id'))
        batch_op.drop_index(batch_op.f('ix_service_applications_id'))
        batch_op.drop_index(batch_op.f('ix_service_applications_department_id'))
        batch_op.drop_index(batch_op.f('ix_service_applications_citizen_id'))

    op.drop_table('service_applications')
    with op.batch_alter_table('data_mapping_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_mapping_rules_mapping_id'))

    op.drop_table('data_mapping_rules')
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_public_id'))
        batch_op.drop_index(batch_op.f('ix_services_platform_id'))
        batch_op.drop_index(batch_op.f('ix_services_id'))
        batch_op.drop_index(batch_op.f('ix_services_department_id'))
        batch_op.drop_index(batch_op.f('ix_services_code'))

    op.drop_table('services')
    with op.batch_alter_table('data_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_mappings_target_system_id'))
        batch_op.drop_index(batch_op.f('ix_data_mappings_status'))
        batch_op.drop_index(batch_op.f('ix_data_mappings_source_system_id'))
        batch_op.drop_index(batch_op.f('ix_data_mappings_public_id'))
        batch_op.drop_index(batch_op.f('ix_data_mappings_integration_id'))

    op.drop_table('data_mappings')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role_id'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_public_id'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_department_id'))

    op.drop_table('users')
    with op.batch_alter_table('connected_systems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connected_systems_slug'))
        batch_op.drop_index(batch_op.f('ix_connected_systems_public_id'))
        batch_op.drop_index(batch_op.f('ix_connected_systems_id'))
        batch_op.drop_index(batch_op.f('ix_connected_systems_department_id'))

    op.drop_table('connected_systems')
    op.drop_table('roles')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_public_id'))
        batch_op.drop_index(batch_op.f('ix_departments_id'))
        batch_op.drop_index(batch_op.f('ix_departments_code'))

    op.drop_table('departments')
    # ### end Alembic commands ###
