/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as CitizenRouteImport } from './routes/citizen'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppFeatureRouteImport } from './routes/_app.$feature'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as CitizenLoginRouteImport } from './routes/citizen.login'
import { Route as CitizenRegisterRouteImport } from './routes/citizen.register'
import { Route as AppFeatureIdRouteImport } from './routes/_app.$feature.$id'
import { Route as AppApplicationsIdRouteImport } from './routes/_app.applications.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRoute = CitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFeatureRoute = AppFeatureRouteImport.update({
  id: '/$feature',
  path: '/$feature',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const CitizenLoginRoute = CitizenLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenRegisterRoute = CitizenRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => CitizenRoute,
} as any)
const AppFeatureIdRoute = AppFeatureIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppFeatureRoute,
} as any)
const AppApplicationsIdRoute = AppApplicationsIdRouteImport.update({
  id: '/applications/$id',
  path: '/applications/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/citizen': typeof CitizenRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/signup': typeof SignupRoute
  '/$feature': typeof AppFeatureRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/citizen/login': typeof CitizenLoginRoute
  '/citizen/register': typeof CitizenRegisterRoute
  '/$feature/$id': typeof AppFeatureIdRoute
  '/applications/$id': typeof AppApplicationsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/citizen': typeof CitizenRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/signup': typeof SignupRoute
  '/$feature': typeof AppFeatureRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/citizen/login': typeof CitizenLoginRoute
  '/citizen/register': typeof CitizenRegisterRoute
  '/$feature/$id': typeof AppFeatureIdRoute
  '/applications/$id': typeof AppApplicationsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/citizen': typeof CitizenRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/signup': typeof SignupRoute
  '/_app/$feature': typeof AppFeatureRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/citizen/login': typeof CitizenLoginRoute
  '/citizen/register': typeof CitizenRegisterRoute
  '/_app/$feature/$id': typeof AppFeatureIdRoute
  '/_app/applications/$id': typeof AppApplicationsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/citizen'
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/signup'
    | '/$feature'
    | '/dashboard'
    | '/citizen/login'
    | '/citizen/register'
    | '/$feature/$id'
    | '/applications/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/citizen'
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/signup'
    | '/$feature'
    | '/dashboard'
    | '/citizen/login'
    | '/citizen/register'
    | '/$feature/$id'
    | '/applications/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/citizen'
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/signup'
    | '/_app/$feature'
    | '/_app/dashboard'
    | '/citizen/login'
    | '/citizen/register'
    | '/_app/$feature/$id'
    | '/_app/applications/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CitizenRoute: typeof CitizenRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OtpRoute: typeof OtpRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen': {
      id: '/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$feature': {
      id: '/_app/$feature'
      path: '/$feature'
      fullPath: '/$feature'
      preLoaderRoute: typeof AppFeatureRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/citizen/login': {
      id: '/citizen/login'
      path: '/login'
      fullPath: '/citizen/login'
      preLoaderRoute: typeof CitizenLoginRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/register': {
      id: '/citizen/register'
      path: '/register'
      fullPath: '/citizen/register'
      preLoaderRoute: typeof CitizenRegisterRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/_app/$feature/$id': {
      id: '/_app/$feature/$id'
      path: '/$id'
      fullPath: '/$feature/$id'
      preLoaderRoute: typeof AppFeatureIdRouteImport
      parentRoute: typeof AppFeatureRoute
    }
    '/_app/applications/$id': {
      id: '/_app/applications/$id'
      path: '/applications/$id'
      fullPath: '/applications/$id'
      preLoaderRoute: typeof AppApplicationsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppFeatureRouteChildren {
  AppFeatureIdRoute: typeof AppFeatureIdRoute
}

const AppFeatureRouteChildren: AppFeatureRouteChildren = {
  AppFeatureIdRoute: AppFeatureIdRoute,
}

const AppFeatureRouteWithChildren = AppFeatureRoute._addFileChildren(
  AppFeatureRouteChildren,
)

interface AppRouteChildren {
  AppFeatureRoute: typeof AppFeatureRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppApplicationsIdRoute: typeof AppApplicationsIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFeatureRoute: AppFeatureRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppApplicationsIdRoute: AppApplicationsIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CitizenRouteChildren {
  CitizenLoginRoute: typeof CitizenLoginRoute
  CitizenRegisterRoute: typeof CitizenRegisterRoute
}

const CitizenRouteChildren: CitizenRouteChildren = {
  CitizenLoginRoute: CitizenLoginRoute,
  CitizenRegisterRoute: CitizenRegisterRoute,
}

const CitizenRouteWithChildren =
  CitizenRoute._addFileChildren(CitizenRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CitizenRoute: CitizenRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OtpRoute: OtpRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
